spring:
  application:
    name: hmdp
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  profiles:
    active: 'druid'
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug   # 日志